In [4]:
import numpy as np

In [5]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

## Importing Data

In [6]:
raw_data = np.genfromtxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/loan-data.csv', 
                         delimiter = ';', 
                         skip_header = 1, 
                         autostrip = True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [7]:
raw_data.shape

(10000, 14)

## Checking Missing Value

In [8]:
# Test element-wise for NaN and return result as a boolean array.
np.isnan(raw_data).sum()

88005

## Splitting The Dataset

In [9]:
raw_data_mean = np.nanmean(raw_data, axis = 0)
raw_data_mean

C:\Users\hp\AppData\Local\Temp\ipykernel_4952\1812266064.py:1: RuntimeWarning: Mean of empty slice
  raw_data_mean = np.nanmean(raw_data, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
# Find the indices of array elements that are non-zero, grouped by element.
# argwhere will result in boolean (True or False)

numeric = np.argwhere(np.isnan(raw_data_mean) == False).squeeze()
numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [11]:
string = np.argwhere(np.isnan(raw_data_mean)).squeeze()
string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

## Re-importing Data

In [12]:
filling_value = np.nanmax(raw_data) + 1
numeric_data = np.genfromtxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/loan-data.csv', 
                             delimiter = ';', 
                             autostrip = True,
                             skip_header = 1, 
                             usecols = numeric, 
                             filling_values = filling_value)
numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [13]:
string_data = np.genfromtxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/loan-data.csv', 
                             delimiter = ';', 
                             autostrip = True, 
                             dtype = str,
                             skip_header = 1, 
                             usecols = string)
string_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

## Columns

In [14]:
column_name = np.genfromtxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/loan-data.csv', 
                             delimiter = ';', 
                             autostrip = True,
                             skip_footer = raw_data.shape[0], 
                             dtype = str)
column_name

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [15]:
numeric_column = column_name[numeric]
numeric_column

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [16]:
string_column = column_name[string]
string_column

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Manipulating String Data

### Issue Date

In [17]:
string_column[0] = 'issue_date'
string_column

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
np.unique(string_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [19]:
string_data[:,0] = np.chararray.strip(string_data[:,0], '-15')
np.unique(string_data[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [20]:
months = np.array (['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [21]:
# np.where is used with the condition. It served almost the same as conditional IF in excel.

for i in range(13):
    string_data[:,0] = np.where(string_data[:,0] == months[i], i, string_data[:,0])
np.unique(string_data[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [22]:
np.unique(string_data[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [23]:
status_bad = np.array(['', 'Charged Off', 'Late (31-120 days)', 'Issued', 'Default'])

In [24]:
# Return elements chosen from `x` or `y` depending on `condition`.

string_data[:,1] = np.where(np.isin(string_data[:,1], status_bad), 0, 1)
np.unique(string_data[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [25]:
np.unique(string_data[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [26]:
string_data[:,2] = np.chararray.strip(string_data[:,2], ' months')
np.unique(string_data[:,2])

array(['', '36', '60'], dtype='<U69')

In [27]:
string_column[2] = 'term_months'
string_column

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [28]:
string_data[:,2] = np.where(string_data[:,2] == '', '60', string_data[:,2])
np.unique(string_data[:,2])

array(['36', '60'], dtype='<U69')

### Grade & Sub-grade

In [29]:
np.unique(string_data[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [30]:
np.unique(string_data[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [31]:
string_data[:,4] = np.where(string_data[:,4] == '', 'H1', string_data[:,4])

In [32]:
np.unique(string_data[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [33]:
np.unique(string_data[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [34]:
string_column = np.delete(string_column, 3)
string_column

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
string_data = np.delete(string_data, 3, axis = 1)

In [36]:
# 37 jumlah unique value di string_data[:,3]

keys = list(np.unique(string_data[:,3]))
values = list(range(1,37))
dict_sub_grade = dict(zip(keys, values))
print (dict_sub_grade, end=' ')

{'A1': 1, 'A2': 2, 'A3': 3, 'A4': 4, 'A5': 5, 'B1': 6, 'B2': 7, 'B3': 8, 'B4': 9, 'B5': 10, 'C1': 11, 'C2': 12, 'C3': 13, 'C4': 14, 'C5': 15, 'D1': 16, 'D2': 17, 'D3': 18, 'D4': 19, 'D5': 20, 'E1': 21, 'E2': 22, 'E3': 23, 'E4': 24, 'E5': 25, 'F1': 26, 'F2': 27, 'F3': 28, 'F4': 29, 'F5': 30, 'G1': 31, 'G2': 32, 'G3': 33, 'G4': 34, 'G5': 35, 'H1': 36} 

In [37]:
for i in np.unique(string_data[:,3]):
    string_data[:,3] = np.where(string_data[:,3] == i, dict_sub_grade[i], string_data[:,3])

In [38]:
np.unique(string_data[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [39]:
np.unique(string_data[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [40]:
string_data[:,4] = np.where(((string_data[:,4] == '') | (string_data[:,4] == 'Not Verified')), 0, 1)

In [41]:
np.unique(string_data[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [42]:
np.unique(string_data[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [43]:
string_data[:,5] = np.chararray.strip(string_data[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [44]:
string_data[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [45]:
numeric_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [46]:
np.array_equal(string_data[:,5].astype(dtype = int), numeric_data[:,0].astype(dtype = int))

True

In [47]:
string_data = np.delete(string_data, 5, axis = 1)

In [48]:
string_column = np.delete(string_column, 5)
string_column

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

### State Address

In [49]:
np.unique(string_data[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [50]:
string_column[5] = 'state_address'
string_column

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [51]:
string_data[:,5] = np.where(string_data[:,5] == '', 0 , string_data[:,5])

In [52]:
np.unique(string_data[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [53]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [54]:
string_data[:,5] = np.where(np.isin(string_data[:,5], states_west), 1, string_data[:,5])
string_data[:,5] = np.where(np.isin(string_data[:,5], states_south), 2, string_data[:,5])
string_data[:,5] = np.where(np.isin(string_data[:,5], states_midwest), 3, string_data[:,5])
string_data[:,5] = np.where(np.isin(string_data[:,5], states_east), 4, string_data[:,5])

In [55]:
np.unique(string_data[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Number

In [56]:
string_data

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [57]:
string_data = string_data.astype(dtype = int)

In [58]:
string_data

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [59]:
string_column

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

## Manipulating Numeric Column

In [60]:
numeric_column

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [61]:
numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [62]:
np.isnan(numeric_data).sum()

0

### ID

In [63]:
filling_value

68616520.0

In [64]:
np.isin(numeric_data[:,0], filling_value).sum()

0

### Loan Amount

In [65]:
numeric_data[:,1]

array([   35000.,    30000.,    15000., ...,    10000., 68616520.,    10000.])

In [66]:
filling = np.nanmin(numeric_data, axis = 0)
filling

array([373332.  ,   1000.  ,   1000.  ,      6.  ,     31.42,      0.  ])

In [67]:
numeric_data[:,1] = np.where(numeric_data[:,1] == filling_value, filling[1], numeric_data[:,1])

In [68]:
numeric_data[:,1]

array([35000., 30000., 15000., ..., 10000.,  1000., 10000.])

### Funded Amount, Rate, Installment, Funded Payment

In [69]:
for i in [2,3,4,5]:
    numeric_data[:,i] = np.where(numeric_data[:,i] == filling_value, filling[i], numeric_data[:,i])

In [70]:
numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        6.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,        6.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        6.  ,       31.42,     2185.64],
       [46154151.  ,     1000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        6.  ,      309.97,      301.9 ]])

## Currency Change

### Exchange Rate

In [71]:
EUR_USD = np.genfromtxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/EUR-USD.csv', 
                        delimiter = ',', 
                        autostrip = True, 
                        usecols = 3, 
                        skip_header = 1)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [72]:
string_data[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [73]:
np.mean(EUR_USD)

1.1056866943836212

In [74]:
exchange_rate = string_data[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, EUR_USD[i-1], exchange_rate)
    
exchange_rate = np.where(exchange_rate == 0, np.mean(EUR_USD), exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [75]:
exchange_rate.shape

(10000,)

In [76]:
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [77]:
# Stack arrays in sequence horizontally (column wise).

numeric_data = np.hstack((numeric_data, exchange_rate))
numeric_data

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,     2185.64,        1.12],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [78]:
numeric_column = np.concatenate((numeric_column, np.array(['exchange_rate'])))
numeric_column

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

### USD to EUR

In [79]:
usd_column = np.array([1,2,4,5])

In [80]:
for i in usd_column:
    numeric_data = np.hstack((numeric_data, np.reshape(numeric_data[:,i] / numeric_data[:,6], (10000,1))))

In [81]:
numeric_data.shape

(10000, 11)

### Naming The Header

In [82]:
header_eur = np.array([column_name + '_EUR' for column_name in numeric_column[usd_column]])

In [83]:
header_eur

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [84]:
numeric_column = np.concatenate((numeric_column, header_eur))

In [85]:
numeric_column

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [86]:
numeric_column[usd_column] = np.array([column_name + '_USD' for column_name in numeric_column[usd_column]])

In [87]:
numeric_column

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [88]:
numeric_column_index = [0, 3, 6, 1, 7, 2, 8, 4, 9, 5, 10]

In [89]:
numeric_column = numeric_column[numeric_column_index]
numeric_column

array(['id', 'int_rate', 'exchange_rate', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD',
       'funded_amnt_EUR', 'installment_USD', 'installment_EUR', 'total_pymnt_USD',
       'total_pymnt_EUR'], dtype='<U19')

In [90]:
numeric_data = numeric_data[:, numeric_column_index]

In [91]:
numeric_data

array([[48010226.  ,       13.33,        1.1 , ...,     1081.04,     9452.96,     8624.69],
       [57693261.  ,        6.  ,        1.11, ...,      848.86,     4679.7 ,     4232.39],
       [59432726.  ,        6.  ,        1.13, ...,      439.64,     1969.83,     1750.04],
       ...,
       [50415990.  ,        6.  ,        1.12, ...,       28.  ,     2185.64,     1947.47],
       [46154151.  ,       16.55,        1.11, ...,      318.78,     3199.4 ,     2878.63],
       [66055249.  ,        6.  ,        1.09, ...,      283.49,      301.9 ,      276.11]])

### Interest Rate

In [92]:
numeric_data[:,1]

array([13.33,  6.  ,  6.  , ...,  6.  , 16.55,  6.  ])

In [93]:
numeric_data[:,1] = numeric_data[:,1]/100

In [94]:
numeric_data[:,1]

array([0.13, 0.06, 0.06, ..., 0.06, 0.17, 0.06])

## Complete Dataset

In [95]:
# Stack arrays in sequence horizontally (column wise).

loan_data = np.hstack((numeric_data, string_data))

In [96]:
loan_data

array([[48010226.  ,        0.13,        1.1 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,        0.06,        1.11, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,        0.06,        1.13, ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,        0.06,        1.12, ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,        0.17,        1.11, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,        0.06,        1.09, ...,        4.  ,        0.  ,        3.  ]])

In [97]:
np.isnan(loan_data).sum()

0

In [98]:
# Join a sequence of arrays along an existing axis.

header_full = np.concatenate((numeric_column, string_column))

In [99]:
header_full

array(['id', 'int_rate', 'exchange_rate', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD',
       'funded_amnt_EUR', 'installment_USD', 'installment_EUR', 'total_pymnt_USD',
       'total_pymnt_EUR', 'issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

## Sorting Dataset

In [100]:
# np.argsort : Returns the indices that would sort an array.

loan_data = loan_data[np.argsort(loan_data[:,0])]

In [101]:
loan_data

array([[  373332.  ,        0.18,        1.1 , ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,        0.21,        1.1 , ...,       36.  ,        1.  ,        2.  ],
       [  707689.  ,        0.14,        1.12, ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,        0.06,        1.09, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,        0.06,        1.09, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,        0.06,        1.09, ...,        3.  ,        0.  ,        2.  ]])

## Saving Dataset

In [104]:
loan_data = np.vstack((header_full, loan_data))
loan_data

array([['id', 'int_rate', 'exchange_rate', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['id', 'int_rate', 'exchange_rate', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '0.1825', '1.100897192955017', ..., '21.0', '0.0', '1.0'],
       ...,
       ['68614880.0', '0.06', '1.093398094177246', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '0.06', '1.093398094177246', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '0.06', '1.093398094177246', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [103]:
np.savetxt('C:/Users/hp/Downloads/Phyton/S23 - A Loan Data Example with NumPy [DONE]/loan-data-preprocessed.csv', 
           loan_data, 
           fmt = '%s', 
           delimiter = ',')